name: "Feature Request (日本語)"
description: "機能や強化をリクエストします。"
labels: ["triage", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能のリクエストを作成していただきありがとうございます！ 😎

        提出する前に、オープン/クローズされた機能のリクエストを検索してください。以前に、誰かが同じことを尋ねているかもしれません！ 😎

          - [Issues](https://github.com/PolyTorus/polytorus/issues)
          - [Closed Issues](https://github.com/PolyTorus/polytorus/issues?q=is%3Aissue%20state%3Aclosed)
          - [Discussions](https://github.com/PolyTorus/polytorus/discussions)
  - type: textarea
    id: description
    attributes:
      label: "概要"
      description: "このリクエストを1,2行で説明してください。"
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: "問題の主張/正当化"
      description: |
        なぜこの機能がPolyTorusに追加されるべきか、有効な理由を提供してください。

        この機能が遭遇した問題に関連している場合は、それも説明してください。
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "提案する解決策やAPI"
      description: 理想的な設計やAPIへのコードスニペット、またはリンクを提供してください。
      placeholder: |
        ユーザーとして、____ したとき、____ が起こると予想していましたが、代わりに ____ が起こりました。

        あなたが描く未来予想図:
        1. '...'に行く
        2. '....'をクリックする
        3. ....
  - type: textarea
    id: additional-information
    attributes:
      label: "追加情報"
      description: この機能を理解または実装するのに役立つリソース（リンク、スクリーンショットなど）がありますか？
  - type: markdown
    attributes:
      value: