name: Format by `cargo fmt`

on:
  push:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/dtolnay/rust-toolchain
      - name: Install rust components
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: format
        run: cargo fmt --all --check
